/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package art.gallery;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Deepak
 */
public class Admin_Painting extends javax.swing.JFrame {

    Connection conn;
    /**
     * Creates new form Admin_Painting
     */
    
    String filepath=null;
    PreparedStatement ps;
    public Admin_Painting() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        caption_lbl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cost_lbl = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        c_lbl = new javax.swing.JComboBox<>();
        a_id = new javax.swing.JLabel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        name = new javax.swing.JLabel();
        c_lbl1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        aid1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        pic.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 70, -1, -1));

        caption_lbl.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        caption_lbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        caption_lbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caption_lblActionPerformed(evt);
            }
        });
        jPanel1.add(caption_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 156, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Caption:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, 30));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Year:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 60, 30));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Category:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add paintings");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 330, 90));

        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cost:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        cost_lbl.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cost_lbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cost_lbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cost_lblKeyTyped(evt);
            }
        });
        jPanel1.add(cost_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 156, -1));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Object:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, 28));

        c_lbl.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        c_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c_lbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                c_lblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        c_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c_lblMouseEntered(evt);
            }
        });
        c_lbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_lblActionPerformed(evt);
            }
        });
        jPanel1.add(c_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 156, -1));

        a_id.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        a_id.setForeground(new java.awt.Color(255, 255, 255));
        a_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(a_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 81, 32));
        jPanel1.add(jYearChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 160, 30));

        name.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 80, 140, 40));

        c_lbl1.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        c_lbl1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Traditional", "People", "Nature", "Cars", "Animals" }));
        c_lbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c_lbl1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                c_lbl1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        c_lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c_lbl1MouseEntered(evt);
            }
        });
        c_lbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_lbl1ActionPerformed(evt);
            }
        });
        jPanel1.add(c_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 156, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, -1, -1));

        aid1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        aid1.setForeground(new java.awt.Color(255, 255, 255));
        aid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aid1.setText("Name:");
        jPanel1.add(aid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 81, 32));

        name1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name1.setText("ID");
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 81, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/bgimg/cool-art-backgrounds-018.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 620));

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        /*JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();

        filename =f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(pic.getWidth(), pic.getHeight(), Image.SCALE_DEFAULT));
        pic.setIcon(imageIcon);
        try {

            File image = new File(filename);
            FileInputStream fis = new FileInputStream (image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int readNum; (readNum=fis.read(buf))!=-1; ){

                bos.write(buf,0,readNum);
            }
            person_image=bos.toByteArray();
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
        */

        JFileChooser chooser=new JFileChooser(new File("E:\\"));

            chooser.setMultiSelectionEnabled(false);
            chooser.setVisible(true);

            chooser.showOpenDialog(this);

            File file=chooser.getSelectedFile();
            if(file!=null){filepath=file.getPath();}
            if(filepath!=null){
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(filepath).getImage().getScaledInstance(pic.getWidth(), pic.getHeight(), Image.SCALE_DEFAULT));
                pic.setIcon(imageIcon);

            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void c_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_lblMouseEntered
        
    }//GEN-LAST:event_c_lblMouseEntered

    private void c_lblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_lblActionPerformed
        
    }//GEN-LAST:event_c_lblActionPerformed

    private void c_lblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_c_lblAncestorAdded
          try
        {
            OpenDatabase();
            String query="select * from artist where a_id='"+a_id.getText()+"'";
            Statement st = conn.createStatement();
            ResultSet rs1 = st.executeQuery(query);
            while (rs1.next()) {
                c_lbl.addItem(rs1.getString(7));
                c_lbl.addItem(rs1.getString(8));
                c_lbl.addItem(rs1.getString(9));
            }
            rs1.close();
            CloseDatabase();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_c_lblAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int id=Integer.parseInt(a_id.getText());
        String caption=caption_lbl.getText();
            int year=jYearChooser1.getYear();
            String ctg=(c_lbl.getSelectedItem().toString());
            String obj=(c_lbl1.getSelectedItem().toString());
            int cost=Integer.parseInt(cost_lbl.getText());
        try
        {
            
             FileInputStream fileInputStream=new FileInputStream(filepath);
            byte b[]=new byte[fileInputStream.available()];
            fileInputStream.read(b);
            fileInputStream.close();
            OpenDatabase();
            Statement st=conn.createStatement();
            ps=conn.prepareStatement("insert into painting values(?,?,?,?,?,?,?,?,?)");
            ps.setInt(1, 0);
            ps.setInt(2,id);
            ps.setString(3, caption);
            ps.setInt(4, year);
            ps.setString(5, ctg);
            ps.setString(6, obj);
           ps.setInt(7,cost);
            ps.setBytes(8, b);
            ps.setInt(9, 0);
            int val=ps.executeUpdate();
            if(val>=1)
            JOptionPane.showConfirmDialog(null, "Painting has been Uploaded", "Signup", JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE);
            Admin_Main_Page a2=new Admin_Main_Page();
            a2.id.setText(a_id.getText());
            a2.name.setText(name.getText());
            a2.setVisible(true);
            this.dispose();
            CloseDatabase();
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
            JOptionPane.showConfirmDialog(null, "Painting does not uploaded", "Result", JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE);
            
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void c_lbl1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_c_lbl1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_c_lbl1AncestorAdded

    private void c_lbl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_lbl1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_c_lbl1MouseEntered

    private void c_lbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_lbl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_lbl1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Admin_Main_Page a2=new Admin_Main_Page();
        a2.id.setText(a_id.getText());
        a2.name.setText(name.getText());
        a2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cost_lblKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cost_lblKeyTyped
                char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_cost_lblKeyTyped

    private void caption_lblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caption_lblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caption_lblActionPerformed

    public void OpenDatabase()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pri?zeroDateTimeBehavior=convertToNull","root","");  
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    public void CloseDatabase()
    {
        try 
        {
            conn.close();
        } 
        catch (SQLException e) 
        {
             e.printStackTrace();
        }           
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Painting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Painting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Painting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Painting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Painting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel a_id;
    public javax.swing.JLabel aid1;
    private javax.swing.JComboBox<String> c_lbl;
    private javax.swing.JComboBox<String> c_lbl1;
    private javax.swing.JTextField caption_lbl;
    private javax.swing.JTextField cost_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    public javax.swing.JLabel name;
    public javax.swing.JLabel name1;
    private javax.swing.JLabel pic;
    // End of variables declaration//GEN-END:variables
}
